apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: engineers-capacity
  description: Engineers capacity
  tags:
    - java
    - engineers
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: audio-playback
