apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: manual-testing-api
  description: Manual Testing API
  tags:
    - java
spec:
  type: service
  lifecycle: experimental
  owner: team-b
  system: testing
