apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wayback-archive-ingestion
  title: Wayback archive ingestion
  description: Ingestion subsystem of the Wayback Archive
  annotations:
    github.com/project-slug: roadiehq/demo-data
  tags:
    - java
    - demo
spec:
  type: service
  lifecycle: production
  owner: team-delta
  subcomponentOf: wayback-archive
