apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wayback-archive
  title: Wayback archive
  description: Archive of the wayback machine
spec:
  type: service
  lifecycle: production
  owner: team-alpha
  providesApis:
    - wayback-archive
