apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wayback-search
  description: Search of the wayback machine
  annotations:
    buildkite.com/project-slug: [ 'RoadieHQ/demo-data' ]
spec:
  type: service
  lifecycle: production
  owner: team-alpha
  providesApis:
    - wayback-search
  consumesApis:
    - wayback-archive
