apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-api
  title: test search API
  description: Search API test
spec:
  type: openapi
  lifecycle: production
  owner: team-alpha
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/dab6854d4d599aafb0eb36e6c7ae1fe0c37509b7/APIs/gettyimages.com/3/openapi.yaml
